### ISSUE TITLE
LoginUserToAad throws an AadServiceException

### ISSUE THREAD

**Issue by TVDKoni** [PartnerCenterSamples/Partner-Center-SDK-Samples#1]
Following code line in LoginUserToAad produces an exception:
return authContext.AcquireToken(
                Properties.Settings.Default.ResourceUrl,
                Properties.Settings.Default.AppId,
                userCredentials);

Exception text:
AADSTS90014: The request body must contain the following parameter: 'client_secret or client_assertion'

Do I can add these request bodies somehow? Can I use for UserAuthentication.ApplicationId the id from AppAuthentication.ApplicationId?

**Comment by RaedJarrar** [comment]
This indicates that an AD web application Id is passed. This type of AD applications requires a client secret. You should use a native AD web app instead. This should fix this problem.
