### ISSUE TITLE
US Country not currently supported

### ISSUE THREAD

**Issue by AlexanderMer** [PartnerCenterSamples/Partner-Center-SDK-Samples#10]
The _Create new customer_ scenario throws a bad request exception code 20000, saying Current country not supported which by default is set to _US_.  Changing country to a valid  _GB_ address  in _CreateCustomer.RunScenario_  works however. 
In my case I removed the State field, changed country to GB and switched city and postal code to some random place in England.

**Comment by tameemansari** [comment]
Its likely that your partner tenant cannot transact in the US territory. The API honors the [regional authorization rules](https://msdn.microsoft.com/partner-center/regional-authorization-overview) hence it is not allowing you to create a customer in US if your territory / region is under EFTA.
