### ISSUE TITLE
SubscriptionId in Azure Subscription Utilization Records in case sensitive

### ISSUE THREAD

**Issue by vidarw** [PartnerCenterSamples/Partner-Center-SDK-Samples#12]
The API only works with uppercase GUIDS in /subscriptions/

The following request works:
`https://api.partnercenter.microsoft.com/v1/customers/91fafcd9-xxxx-xxxx-xxxx-a8f2c544f835/subscriptions/C7F6819F-XXXX-XXXX-XXXX-8F2DFB6BF65D/utilizations/azure?start_time=2017-01-28T00%3A00%3A00Z&end_time=2017-01-31T23%3A59%3A59Z&granularity=Daily&show_details=True&size=100`

Running the following request:
`https://api.partnercenter.microsoft.com/v1/customers/91fafcd9-xxxx-xxxx-xxxx-a8f2c544f835/subscriptions/c7f6819f-xxxx-xxxx-xxxx-8f2dfb6bf65d/utilizations/azure?start_time=2017-01-28T00%3A00%3A00Z&end_time=2017-01-31T23%3A59%3A59Z&granularity=Daily&show_details=True&size=100`

Results in:
`{"code":3000,"description":"A subscription with the provided ID was not found under this customer","data":["subscription_id"],"source":"PartnerFD"}`

Notice that parts of the GUIDs are replaced for privacy reasons.

**Comment by alidhia** [comment]
Hi vidarw,

Thanks for bringing this issue to our attention! the issue has been fixed and will be live in few days
