### ISSUE TITLE
The supplied role does not have the rights to perform the requested operation

### ISSUE THREAD

**Issue by BukeMan** [PartnerCenterSamples/Partner-Center-SDK-Samples#14]
I get this error when trying to run [Update a customer's billing profile](https://msdn.microsoft.com/en-us/library/partnercenter/mt634718.aspx) scenario with standalone App authentication. In documentation, in prerequisites section, it says that this scenario supports both App+User and App authentication. Why do I get this error though?

**Comment by alidhia** [comment]
Hi BukeMan,

You are correct, the scenario you mentioned support both App and App+User authentications, however the samples for this feature that you see here in this sample project was written to authenticate with App+User and not App only.

**Comment by rpatnaik71** [comment]
Hi,
I'm getting this error when I try to perform any kind of operation. I referred the configuration process of authentication. I'm not sure where I'm going wrong. All I need to do is pull some usage records.

**Comment by alidhia** [comment]
Hi @rpatnaik71 ,

as mentioned earlier in this thread, most of the samples in the project work with App+User authentication scheme. if you are using the right scheme and still facing errors, please create a new issue so we can track it correctly.

Thanks,
Ali
