### ISSUE TITLE
AADSTS65001

### ISSUE THREAD

**Issue by Heiner-Mueller** [PartnerCenterSamples/Partner-Center-SDK-Samples#15]
I get an error that leaves me puzzled. 
"UserCredential" does not contain a constructor, that accepts 2 Arguments.

When I try to look at the definiton, I see this, which confirms the error.

     public class UserCredential{

     public UserCredential();  
      
     public UserCredential(string userName);

     public string UserName { get; }}}

And I just don't seem to get what the problem might be. Why would a codesample use this? Am I missing something?

**Comment by Heiner-Mueller** [comment]
according to https://stackoverflow.com/questions/37443977/microsoft-identitymodel-clients-activedirectory-usercredential-does-not-take-2-p you should be using `UserPasswordCredential`

**Comment by AntJ101** [comment]
Change function 'LoginUserToAad' in ScenarioContext.cs to

private AuthenticationResult LoginUserToAad()
        {
            var addAuthority = new UriBuilder(this.Configuration.PartnerService.AuthenticationAuthorityEndpoint)
            {
                Path = this.Configuration.PartnerService.CommonDomain
            };

            UserPasswordCredential oUserPasswordCredential = new UserPasswordCredential(
                this.Configuration.UserAuthentication.UserName,
                this.Configuration.UserAuthentication.Password);

            AuthenticationContext authContext = new AuthenticationContext(addAuthority.Uri.AbsoluteUri);

            AuthenticationResult oAuthenticationResult = authContext.AcquireTokenAsync(
                this.Configuration.UserAuthentication.ResourceUrl.OriginalString,
                this.Configuration.UserAuthentication.ApplicationId,
                oUserPasswordCredential).Result ;

            return oAuthenticationResult;
        }

**Comment by AntJ101** [comment]
Although no matter which version of ADAL I see error 'AADSTS70002: The request body must contain the following parameter: 'client_secret or client_assertion' when performing a UserPartnerOperations. Any one any pointers?

**Comment by alidhia** [comment]
@Heiner-Mueller, it seems you have updated the ADAL library to a version later than 2.16.204221202 and thus you are getting those problems. please try to revert the Microsoft.IdentityModel.Clients.ActiveDirectory to said version as we have not updated our project samples to the latest ADAL version

@AntJ101 please make sure you are using the correct authentication scheme in the scenario you are testing, most of the scenarios in the sample support UserAuthentication, few samples support the AppAuthentication

**Comment by AntJ101** [comment]
@Heiner-Mueller Hi, Thanks for your reply, I have also tested with Microsoft.IdentityModel.Clients.ActiveDirectory -Version 2.16.204221202, I see the same error (AADSTS70002) when using UserAuthentication. Perhaps I have an incorrect App ID, or CommonDomain. My common Domain is set to 'Common', does the following look correct?
  <PartnerServiceSettings>
    <add key="PartnerServiceApiEndpoint" value="https://api.partnercenter.microsoft.com"/>
    <add key="AuthenticationAuthorityEndpoint" value="https://login.windows.net/"/>
    <add key="GraphEndpoint" value="https://graph.windows.net"/>
    <add key="CommonDomain" value="common"/>
  </PartnerServiceSettings>
 <UserAuthentication>
    <add key="ApplicationId" value="AppID that is register in AAD (set to Native)"/>
    <add key="ResourceUrl" value="https://api.partnercenter.microsoft.com"/>
    <add key="RedirectUrl" value="http://localhost"/>
    <add key="UserName" value="AADAdmin@ADomain.onmicrosoft.com"/>
    <add key="Password" value="AADaDMIN Password"/>
  </UserAuthentication>

  <AppAuthentication>
    <add key="ApplicationId" value="Same AppID as UserAuthentication.ApplicationId "/>
    <add key="ApplicationSecret" value="Key for App"/>
    <add key="Domain" value="ADomain.onmicrosoft.com"/>
  </AppAuthentication>

Thanks
Ant

**Comment by alidhia** [comment]
@AntJ101 , it seems there was an issue when you pasted your configs as I cannot see them, however, setting the domain name to "common" seems correct, I would say make sure the ApplicationId you are using is a native app Id and not a web app id

**Comment by Heiner-Mueller** [comment]
@alidhia: I can't find the Version 2.16.204221202 or earlier that is not 1.0.5
The earliest one I got was 2.22.302111727. Naturally, reverting to this Version leads to only more erros.


using the fix I found on above stackoverflow link, had me change the last couple of lines in the `ScenarioContext.cs` file to
`UserCredential userCredentials = new UserPasswordCredential(
                this.Configuration.UserAuthentication.UserName,
                this.Configuration.UserAuthentication.Password);

            AuthenticationContext authContext = new AuthenticationContext(addAuthority.Uri.AbsoluteUri);

            return authContext.AcquireTokenAsync(
                this.Configuration.UserAuthentication.ResourceUrl.OriginalString,
                this.Configuration.UserAuthentication.ApplicationId,
                userCredentials).Result;`

**Comment by AntJ101** [comment]
@alidhia, @Heiner-Mueller 
 In order to get 2.16.204221202 you need to use the Powershell command Install-Package Microsoft.IdentityModel.Clients.ActiveDirectory -Version 2.16.204221202

I switched from using an AAD Native App to a CSP Native App and all is now well.

Thanks
Ant

**Comment by Heiner-Mueller** [comment]
Ok, Now that I did the version downgrade, I get another Error and that is this:

In the File GetCustomerServiceCostsSummary.cs, it says Microsoft.Store.PartnerCenter.Models is not found. 

Which configuration of NuGet Packages is the one I should use? Because trying out every possible permutation is tedious

**Comment by Heiner-Mueller** [comment]
Okay, I'm in a bit of a kerfuffle here. After using your fix @AntJ101, I was able to get the package to the desired version. Now I keep running into different problems and the logs are unfortunately in german. I'm gonna paste them anyway, because maybe you can get the gist of it

> System.IO.FileLoadException: Die Datei oder Assembly "Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.14.1.10, Culture=neutral, PublicKeyToken=31bf3856ad364e35" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
> Dateiname: "Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.14.1.10, Culture=neutral, PublicKeyToken=31bf3856ad364e35" ---> System.IO.FileLoadException: Die Datei oder Assembly "Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35" oder eine Abhängigkeit davon wurde nicht gefunden. Die gefundene Manifestdefinition der Assembly stimmt nicht mit dem Assemblyverweis überein. (Ausnahme von HRESULT: 0x80131040)
> Dateiname: "Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35"

> 
> > 
> > === Zustandsinformationen vor Bindung ===
> > LOG: DisplayName = Microsoft.IdentityModel.Clients.ActiveDirectory, Version=2.16.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35
> >  (Fully-specified)
> > LOG: Appbase = file:///C:/Users/vin0256/Documents/Visual Studio 2017/Projects/Microsoft/Partner-Center-SDK-Samples-master/Source/Partner Center SDK Samples/bin/Debug/
> > LOG: Ursprünglicher PrivatePath = NULL
> > Aufruf von Assembly : Microsoft.Store.PartnerCenter.Samples, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.
> > ===

> LOG: Diese Bindung startet im default-Load-Kontext.
> LOG: Die Anwendungskonfigurationsdatei wird verwendet: C:\Users\vin0256\Documents\Visual Studio 2017\Projects\Microsoft\Partner-Center-SDK-Samples-master\Source\Partner Center SDK Samples\bin\Debug\Microsoft.Store.PartnerCenter.Samples.exe.Config
> LOG: Die Hostkonfigurationsdatei wird verwendet:
> LOG: Die Computerkonfigurationsdatei von C:\Windows\Microsoft.NET\Framework\v4.0.30319\config\machine.config wird verwendet.
> LOG: In der Anwendungskonfigurationsdatei wurde eine Umleitung gefunden. 2.16.0.0 wird nach 3.14.1.10 umgeleitet.
> LOG: Verweis nach der Richtlinie: Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.14.1.10, Culture=neutral, PublicKeyToken=31bf3856ad364e35
> LOG: Download von neuem URL file:///C:/Users/vin0256/Documents/Visual Studio 2017/Projects/Microsoft/Partner-Center-SDK-Samples-master/Source/Partner Center SDK Samples/bin/Debug/Microsoft.IdentityModel.Clients.ActiveDirectory.DLL.
> WRN: Der Vergleich des Assemblynamens führte zum Konflikt: Hauptversion.
> ERR: Das Setup der Assembly konnte nicht abgeschlossen werden (hr = 0x80131040). Die Suche wurde beendet.
> 
>    bei Microsoft.Store.PartnerCenter.Samples.Context.ScenarioContext.get_UserPartnerOperations()
>    bei Microsoft.Store.PartnerCenter.Samples.Customers.CreateCustomer.RunScenario() in C:\Users\vin0256\Documents\Visual Studio 2017\Projects\Microsoft\Partner-Center-SDK-Samples-master\Source\Partner Center SDK Samples\Customers\CreateCustomer.cs:Zeile 34.
>    bei Microsoft.Store.PartnerCenter.Samples.BasePartnerScenario.Run() in C:\Users\vin0256\Documents\Visual Studio 2017\Projects\Microsoft\Partner-Center-SDK-Samples-master\Source\Partner Center SDK Samples\BasePartnerScenario.cs:Zeile 78.

note: I did use a CSP Web APP and if that just does not work and I should try a Native App, what am I going to use as a resource URL?

**Comment by Heiner-Mueller** [comment]
I got rid of that problem, updating the footer of the App.config file, now I am left with this error once more

> 
> System.ArgumentNullException: Der Wert darf nicht NULL sein.
> Parametername: uriString
>    bei System.Uri..ctor(String uriString)
>    bei Microsoft.Store.PartnerCenter.Samples.Configuration.UserAuthenticationSection.get_ResourceUrl() in C:\Users\vin0256\Documents\Visual Studio 2017\Projects\Microsoft\Partner-Center-SDK-Samples-master\Source\Partner Center SDK Samples\Configuration\UserAuthenticationSection.cs:Zeile 42.
>    bei Microsoft.Store.PartnerCenter.Samples.Context.ScenarioContext.LoginUserToAad() in C:\Users\vin0256\Documents\Visual Studio 2017\Projects\Microsoft\Partner-Center-SDK-Samples-master\Source\Partner Center SDK Samples\Context\ScenarioContext.cs:Zeile 152.
>    bei Microsoft.Store.PartnerCenter.Samples.Context.ScenarioContext.get_UserPartnerOperations() in C:\Users\vin0256\Documents\Visual Studio 2017\Projects\Microsoft\Partner-Center-SDK-Samples-master\Source\Partner Center SDK Samples\Context\ScenarioContext.cs:Zeile 106.
>    bei Microsoft.Store.PartnerCenter.Samples.Customers.CreateCustomer.RunScenario() in C:\Users\vin0256\Documents\Visual Studio 2017\Projects\Microsoft\Partner-Center-SDK-Samples-master\Source\Partner Center SDK Samples\Customers\CreateCustomer.cs:Zeile 34.
>    bei Microsoft.Store.PartnerCenter.Samples.BasePartnerScenario.Run() in C:\Users\vin0256\Documents\Visual Studio 2017\Projects\Microsoft\Partner-Center-SDK-Samples-master\Source\Partner Center SDK Samples\BasePartnerScenario.cs:Zeile 78.

**Comment by AntJ101** [comment]
I had to set App.Config the content of node 'dependentAssembly' with the below before .NET stopped trying to use the latest, even though all projects in my solution referenced 2.16! 
assemblyIdentity name="Microsoft.IdentityModel.Clients.ActiveDirectory" publicKeyToken="31bf3856ad364e35" culture="neutral"
bindingRedirect oldVersion="2.16.204221202" newVersion="2.16.204221202"

**Comment by Heiner-Mueller** [comment]
I did that, still the same output. Could it be that I am using a Web App? If I sould use a native one, what am I going to use as a ResourceUrl?

**Comment by AntJ101** [comment]
Don't think it matters what they are set to for Native, but I have them set to:
add key="ResourceUrl" value="https://api.partnercenter.microsoft.com"
add key="RedirectUrl" value="http://localhost"

**Comment by Heiner-Mueller** [comment]
using a native app and your given values still yields the same results

**Comment by AntJ101** [comment]
Only other thing I did was add a Native App via 'https://partnercenter.microsoft.com/en-us/pcv/apiintegration/appmanagement', previously I was using an AAD Native App, which I thought was the correct thing to do but it appears not to be so.

**Comment by Heiner-Mueller** [comment]
I am now using the same kind of Native App you do, and now, when I try to run the 'Get Paged Customers' Scenario, I get this new error:

> Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS65001: The user or administrator has not consented to use the application with ID '1bf4e0e1-86d1-4127-be39-dadbec82b856'. Send an interactive authorization request for this user and resource.
> Trace ID: cc1f8d90-60df-4478-8465-a8bb62ac1e00
> Correlation ID: 23fc6119-ae84-42c5-8740-13f214c3c71f
> Timestamp: 2017-07-04 12:22:23Z ---> System.Net.WebException: Der Remoteserver hat einen Fehler zurückgegeben: (400) Ungültige Anforderung.
>    bei System.Net.HttpWebRequest.GetResponse()
>    bei Microsoft.IdentityModel.Clients.ActiveDirectory.HttpWebRequestWrapper.<GetResponseSyncOrAsync>d__2.MoveNext()
> --- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
>    bei System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
>    bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    bei Microsoft.IdentityModel.Clients.ActiveDirectory.HttpHelper.<SendPostRequestAndDeserializeJsonResponseAsync>d__0`1.MoveNext()
>    --- Ende der internen Ausnahmestapelüberwachung ---
>    bei Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.RunAsyncTask[T](Task`1 task)
>    bei Microsoft.IdentityModel.Clients.ActiveDirectory.AuthenticationContext.AcquireToken(String resource, String clientId, UserCredential userCredential)
>    bei Microsoft.Store.PartnerCenter.Samples.Context.ScenarioContext.LoginUserToAad() in C:\Users\vin0256\Documents\Visual Studio 2017\Projects\Microsoft\Partner-Center-SDK-Samples-master\Source\Partner Center SDK Samples\Context\ScenarioContext.cs:Zeile 152.
>    bei Microsoft.Store.PartnerCenter.Samples.Context.ScenarioContext.get_UserPartnerOperations() in C:\Users\vin0256\Documents\Visual Studio 2017\Projects\Microsoft\Partner-Center-SDK-Samples-master\Source\Partner Center SDK Samples\Context\ScenarioContext.cs:Zeile 106.
>    bei Microsoft.Store.PartnerCenter.Samples.Customers.GetPagedCustomers.RunScenario() in C:\Users\vin0256\Documents\Visual Studio 2017\Projects\Microsoft\Partner-Center-SDK-Samples-master\Source\Partner Center SDK Samples\Customers\GetPagedCustomers.cs:Zeile 38.
>    bei Microsoft.Store.PartnerCenter.Samples.BasePartnerScenario.Run() in C:\Users\vin0256\Documents\Visual Studio 2017\Projects\Microsoft\Partner-Center-SDK-Samples-master\Source\Partner Center SDK Samples\BasePartnerScenario.cs:Zeile 78.
>         ErrorCode: invalid_grant
>         StatusCode: 400

**Comment by AntJ101** [comment]
humm, Ok I learnt something new, when creating the Apps via CSP portal all it does it create Apps in the AAD, so it isn't doing anything magical. I unregistered my Native App and added a new Native App could still successfully enum Customers. The AAD account I am using is a Admin or AAD, is this the case for you?
Regards
Ant

**Comment by Heiner-Mueller** [comment]
I hope I understand you correctly. I am using an account in the CSP Sandbox Environment where I have global admin rights. I can register native apps, and they show up in the AAD, which is the only way for me to get an Applicationsecret/Key for a native app. Web App lets me create a Key on the CSP page.

**Comment by AntJ101** [comment]
Ok, I think I have a better understanding of CSP now, after some messing around.
In the App.config for the Partner Center SDK Sample set the following:
PartnerServiceSettings.
PartnerServiceSettings
PartnerServiceSettings
AppAuthentication.ApplicationID set to the CSP App Management Web App ID
AppAuthentication.ApplicationSecret set to the CSP App Management Web App Key
AppAuthentication.Domain set to your Sandbox FQDN
UserAuthentication.ApplicationID set to the CSP Native App ID
UserAuthentication.ResourceUrl set to "https://api.partnercenter.microsoft.com"
UserAuthentication.RedirectUrl set to 'http://localhost'
UserAuthentication.UserName set to 'Your Sandbox Admin UserID@Sandbox FDQN'
UserAuthentication.Password set to yuor Sandbox admin password

**Comment by Heiner-Mueller** [comment]
Ok, now I did the same things you did, still nothing. Now I got the feeling that I may have to check with the permissions I gave the Apps. What exactly did you do?

**Comment by AntJ101** [comment]
I left them as default, 
Native App has:
  'Windows Azure Active Directory (Microsoft..)' with 2 delegated Permissions, which is 'Sign in and read user profile' and 'Access the directory as the signed-in user'
  'Microsoft Partner Center (SampleBECApp)' with 1 delegated permission, which is 'Access Partner Center'
Web App has:
 'Windows Azure Active Directory (Microsoft.Azure.ActiveDirectory', one App permission and two delegated permissions, which are 'Read directory data', 'Sign in and read user profile' and 'Access the directory as the signed-in user'


  Note that I too am using a CSP Sandbox.

**Comment by Heiner-Mueller** [comment]
Thank you man! That did it! I can't tel you how glad I am that you helped me!

**Comment by AntJ101** [comment]
no worries, good luck with the rest of it
