### ISSUE TITLE
GetInvoiceLineItems

### ISSUE THREAD

**Issue by maciz84** [PartnerCenterSamples/Partner-Center-SDK-Samples#18]
Hi there,

Could someone please advise as to how I can access the items object which is in the invoiceLineItemEnumerator as below. With most of the other objects in the SDK I can access the Items objects but for this one I cannot get to it?

`                            var invoiceLineItemsCollection = (false ? invoiceOperations.By(invoiceDetail.BillingProvider, invoiceDetail.InvoiceLineItemType).Get() : invoiceOperations.By(Microsoft.Store.PartnerCenter.Models.Invoices.BillingProvider.Office, Microsoft.Store.PartnerCenter.Models.Invoices.InvoiceLineItemType.BillingLineItems).Get(this.invoicePageSize, 0));

                            var invoiceLineItemEnumerator = partnerOperations.Enumerators.InvoiceLineItems.Create(invoiceLineItemsCollection);
                            int pageNumber = 1;

                            foreach (var myobj in invoiceLineItemEnumerator.Current.Items)
                            {
                                Console.WriteLine(myobj.PartnerId);
                            }
                                ;`

The above code only allows me to access The Attributes,BillingProvider and InvoiceLineItemType objects?

your help is much appreciated

**Comment by alidhia** [comment]
Hi maciz84,

the "item" object that you get from the enumerator is of InvoiceLineItem but can be casted to the appropriate line item type, for example LicenseBasedLineItem (which inherets from InvoiceLineItem)

so in your code above you can do 

                        foreach (var myobj in invoiceLineItemEnumerator.Current.Items)
                        {
                            var licenseBasedLineItem = myobj as LicenseBasedLineItem;
                            Console.WriteLine(licenseBasedLineItem.PartnerId);
                        }

Hope this helps

**Comment by maciz84** [comment]
@alidhia thanks for that it worked :)
