### ISSUE TITLE
Some endpoint here for 21V

### ISSUE THREAD

**Issue by huyi2218** [PartnerCenterSamples/Partner-Center-SDK-Samples#19]
<PartnerServiceSettings>

    <add key="PartnerServiceApiEndpoint" value="https://partner.partnercenterapi.microsoftonline.cn" />
    <add key="AuthenticationAuthorityEndpoint" value="https://login.chinacloudapi.cn"/>
    <add key="GraphEndpoint" value="https://microsoftgraph.chinacloudapi.cn"/>
    <add key="CommonDomain" value="common"/>
  </PartnerServiceSettings>

  <UserAuthentication>
    
    <add key="ApplicationId" value="********"/>
    
    <add key="ResourceUrl" value="https://partner.partnercenterapi.microsoftonline.cn"/>
    <add key="RedirectUrl" value="http://localhost"/>
    
    <add key="UserName" value="********"/>
    <add key="Password" value=“*******”"/>
  </UserAuthentication>

  <AppAuthentication>
    
    <add key="ApplicationId" value="********"/>
    
    <add key="ApplicationSecret" value="*******"/>
    
    <add key="Domain" value="*****.partner.onmschina.cn"/>
  </AppAuthentication>

**Comment by alidhia** [comment]
thanks for the info @huyi2218, I will mark this as closed, please let us know if you have any further inquiries
