### ISSUE TITLE
How could get pricing for license-based services using API (REST or Managed) of Microsoft Store Partner Centner

### ISSUE THREAD

**Issue by abdelgrib** [PartnerCenterSamples/Partner-Center-SDK-Samples#21]
The API of Microsoft Store Partner Center using RateCards returns usage-based services (Azure Services) and can't get license-based services pricing ? I could download the Excel file but my question is , is there any way to get pricing for license-based services using API (REST or Managed) of Microsoft Store Partner Center ?

When getting offers using the API, some information are missing like : ERP Price, List Price, Valid-To Date, Valid-From Date ?

**Comment by schuettecarsten** [comment]
Also need this.

**Comment by alidhia** [comment]
We don’t have end points or automatic ways to get License based price list or offer matrix. The work is in our backlog but unfortunately has not meet the prioritization bar yet.
