### ISSUE TITLE
Need more detailed Azure usage/consumption information

### ISSUE THREAD

**Issue by schuettecarsten** [PartnerCenterSamples/Partner-Center-SDK-Samples#22]
Customers request more details usage information for Azure consumption: Usage per day and per resource, at least per resource group. These details are available in enterprise agreements, but not in CSP/partner center.

**Comment by alidhia** [comment]
hey @schuettecarsten , 

please take a loong at this article 
https://msdn.microsoft.com/en-us/library/partnercenter/mt791774.aspx 

Thanks

**Comment by schuettecarsten** [comment]
I've tested the API and requested usage data from 2017-03-01 until 2017-03-31, but the API returned the data from 2017-02-28 until 2017-03-29.

**Comment by alidhia** [comment]
Hi @schuettecarsten,
The Azure utilization API does not have knowledge about the billing system logic. Thus the reconciliation file summary results will not exactly match the results of the utilization API. (this is mentioned at the top fold of the article linked above)
As for the dates offset, can you please create a support ticket in Partner Center with sample code that you are using. The appropriate team will pick up the support ticket and follow up with you.
