### ISSUE TITLE
How to upload files in Partner service request?

### ISSUE THREAD

**Issue by AnandKumar2610** [PartnerCenterSamples/Partner-Center-SDK-Samples#23]
Code here: https://msdn.microsoft.com/en-us/library/partnercenter/mt805812.aspx

**Comment by alidhia** [comment]
hi @AnandKumar2610,

unfortunately we do not support upload files for service requests through API, the only way to upload files for a service request is through Partner Center website

Thanks,
Ali

**Comment by AnandKumar2610** [comment]
thank you for your reply...
why its not supporting through API any security purpose ?

**Comment by jalendar5157** [comment]
Hi Anand- we won't support this functionality through API and this is not related to security. we do few few things in the UI, and pass it to API- that piece is missing in the SDK, we may enable in the future but no concrete plans at the moment

**Comment by AnandKumar2610** [comment]
Hi @jalendar5157 thank you for your reply. Finally no way to upload file through API correct ?

**Comment by alidhia** [comment]
Hi @AnandKumar2610 ,

That is correct, at the moment it is not possible to upload a file related to support tickets through our APIs.

Thanks,
Ali

**Comment by AnandKumar2610** [comment]
Hi @alidhia ,
Thank you for your reply!

**Comment by AnandKumar2610** [comment]
Hi @alidhia , @jalendar5157  I have one question, 
I have successfully created new customer using this api but suppose I'm going to create new customer through microsoft portal at a time how to call my web service from microsoft portal?
Is this possible ???
Thanks in advance
- Anand

**Comment by alidhia** [comment]
Hi, @AnandKumar2610

can you give more clarification about your scenario and what are you trying to do? also, since this is a different issue from uploading a file with a service request programmatically, please post your question in a new issue

Thanks,
Ali

**Comment by AnandKumar2610** [comment]
Ok
