### ISSUE TITLE
How to add existing subscription?

### ISSUE THREAD

**Issue by chadg3** [PartnerCenterSamples/Partner-Center-SDK-Samples#24]
We have this setup and working great but one customer already has a partner managed subscription but would like to manage it. When they log in there doesn't appear to be a way they can do this. It is also not possible for us or Microsoft to delete the current subscription. Is there any way to resolve this?

**Comment by jasonzhang919** [comment]
First, let me try to recap your requirement to see if that's exactly what you want. You have a customer, who previously worked with another partner, and bought a subscription from that partner. Now this customer is working with you and you want to delete or transfer that subscription from the other partner to you.

If the above captures what you want, then
1. If you want to delete the subscription, the customer needs to do it via the previous partner. The previous partner can do it by suspending the subscription. 
2. If you want to transfer, this is not supported in Partner Center currently.

Let me know if you have further questions.

**Comment by chadg3** [comment]
Sorry the issue is under the manage subscriptions. Here is a screen shot. The 365 Enterprise E1 under “customer managed” we purchased using the store front. The Partner managed subscription “Office 365 Business Premium”. That’s one we setup in the partner center vs. store front, so they don’t have the option to “add more licenses”

If I try to add a “Office 365 Business Premium” subscriptions, I receive the error: One or more offers you are trying to add already exists. You can add more licenses to existing subscriptions.

I would love to be able to convert the partner managed subscription to be a customer managed subscription. Otherwise the only option seems to be to suspend the partner managed subscription, wait 90 days for Microsoft to remove it from the tenant and then recreate it again from the store front.

Thanks
------
[signature_1842100852]
Chad Grandy
206.954.8603
888.316.9476
chad@kdhconsulting.net
www.kdhconsulting.net
Please email all requests for support to support@kdhconsulting.net<mailto:support@kdhconsulting.net> or text 206-633-0285 for the fastest response time. A response to direct emails may be delayed.
