### ISSUE TITLE
Meter Rates in NOK

### ISSUE THREAD

**Issue by SalmanMukhtar** [PartnerCenterSamples/Partner-Center-SDK-Samples#25]
Hi,

I am getting meter rates from ratecards in US currency instead of NOK. I have set NOK explicitly in the request but it still does not work.
What is it i am doing wrong?

        protected override void RunScenario()
        {
            var partnerOperations = this.Context.UserPartnerOperations;

            this.Context.ConsoleHelper.StartProgress("Retrieving Azure rate card");
            var azureRateCard = partnerOperations.RateCards.Azure.Get("NOK");
            this.Context.ConsoleHelper.StopProgress();

            this.Context.ConsoleHelper.WriteObject(azureRateCard, "Azure Rate Card");
        }

Salman

**Comment by alidhia** [comment]
Hi @SalmanMukhtar ,

I just tested your scenario and I am getting the correct rates in NOK currency. if you inspect the "azureRateCard" object, what is the value in the "Currency" property

Thanks,
Ali

**Comment by SalmanMukhtar** [comment]
Hi Ali,

Thanks for coming back on this. Seems it's correct.

Regards,
Salman
