### ISSUE TITLE
How to get price list using API ?

### ISSUE THREAD

**Issue by AnandKumar2610** [PartnerCenterSamples/Partner-Center-SDK-Samples#26]
I have successfully created subscription using api but i need price list ...
link here:  https://partnercenter.microsoft.com/en-us/pcv/sales

**Comment by alidhia** [comment]
Hi, @AnandKumar2610,

for usage-based services you can use the Azure rate card API:
https://msdn.microsoft.com/en-us/library/partnercenter/mt791772.aspx

for licensed based services we do not have an API for it currently, the downloadable excel sheet that you pointed out to in your post is the only way to get it in Partner Center.

Ali

**Comment by AnandKumar2610** [comment]
Hi @alidhia 
Thank you for your reply...
