### ISSUE TITLE
Unable to run samples 

### ISSUE THREAD

**Issue by charliejllewellyn** [PartnerCenterSamples/Partner-Center-SDK-Samples#28]
When I try and create a new customer using the samples I get the following errors:

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1729	'UserCredential' does not contain a constructor that takes 2 arguments	Partner Center SDK Samples	C:\Users\Administrator\Downloads\Partner-Center-SDK-Samples\Source\Partner Center SDK Samples\Context\ScenarioContext.cs	141	Active

Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'AuthenticationContext' does not contain a definition for 'AcquireToken' and no extension method 'AcquireToken' accepting a first argument of type 'AuthenticationContext' could be found (are you missing a using directive or an assembly reference?)	Partner Center SDK Samples	C:\Users\Administrator\Downloads\Partner-Center-SDK-Samples\Source\Partner Center SDK Samples\Context\ScenarioContext.cs	147	Active
```

It's interesting that having looked into the second error a little the authcontext only appears to support AcquireTokenAsync.

Apologies this is pretty much the first time I have done anything with .NET so could easily be an mistake in the setup :/

**Comment by alidhia** [comment]
Hi @charliejllewellyn 
This is happening due to the Microsoft.IdentityModel.Clients.ActiveDirectory library version, please try to downgrade the library version to 2.x instead of 3.x

Thanks,
Ali
