### ISSUE TITLE
Get previous month bill for Customer/Subscription/Line Item

### ISSUE THREAD

**Issue by mdsajidfaizan** [PartnerCenterSamples/Partner-Center-SDK-Samples#29]
I am using **Partner center SDK version 1.6**. No where i am able to get the method/property using which i can **get previous month or custom month bill of a customer or subscription**. Can anyone explain how we do. Currently i am able to get current month estimation but not the previous month.

**Comment by alidhia** [comment]
Hi @mdsajidfaizan,

please refer to https://docs.microsoft.com/en-us/partner-center/develop/manage-invoices to see the different ways you can get an invoice programmatically. more specifically, you can get an invoice using the invoice id (whether its the current month or previous ones)

Thanks,
Ali
