### ISSUE TITLE
(Another) The supplied role does not have the rights to perform the requested operation

### ISSUE THREAD

**Issue by wgbartley** [PartnerCenterSamples/Partner-Center-SDK-Samples#35]
I am attempting to perform the Customer samples -> Get Paged customers action and am receiving the error.

The output of the console window is:
```
Get Paged customers
--------------------------------------------------------------------------------


Authenticating user.....

Authenticated!

Querying customers.

Partner Exception:
Error Category: Forbidden
Service Error Payload: null
Context: Request Id: 21dd9fd0-db18-4fe6-8e54-cc06620604fa, Correlation Id: 6a42f4ee-f112-4081-8884-a7369f21ad60, Locale: en-US
Base Description: Microsoft.Store.PartnerCenter.Exceptions.PartnerException: The supplied role does not have the rights to perform the requested operation.
   at Microsoft.Store.PartnerCenter.PartnerService.SynchronousExecute[T](Func`1 operation)
   at Microsoft.Store.PartnerCenter.Customers.CustomerCollectionOperations.Query(IQuery customersQuery)
   at Microsoft.Store.PartnerCenter.Samples.Customers.GetPagedCustomers.RunScenario() in C:\Users\gbartley\Desktop\Partner-Center-SDK-Samples-master\Source\Partner Center SDK Samples\Customers\GetPagedCustomers.cs:line 42
   at Microsoft.Store.PartnerCenter.Samples.BasePartnerScenario.Run() in C:\Users\gbartley\Desktop\Partner-Center-SDK-Samples-master\Source\Partner Center SDK Samples\BasePartnerScenario.cs:line 78


Press Q return to the previous screen or R to repeat the current scenario:
```

I have created the native app registration in Azure AD with the following delegated permissions:
 - Windows Azure Active Directory
   - Access the directory as the signed-in user
   - Read all users' basic profiles
   - Sign in and read user profile
 - Microsoft Partner Center (SampleBECApp)
   - Access Partner Center

The app is registered in Partner Center as a native app using the "Register existing app" link and selected the app that was registered in Azure AD.

The user account I am using is a global admin in both Partner Center and Azure AD.

I have populated the `ApplicationId`, `UserName`, and `Password` values in the `UserAuthentication` section of `App.config` with the values from the Partner Center/Azure AD app registration.

However, in the `AppAuthentication` section of `App.config`, I am unsure of what to enter for the `ApplicationId` and `ApplicationSecret` fields.  The only way I have found to get a secret key is to create a web app registration in Partner Center.  I have been searching and experimenting for days to try to figure this portion out to no avail.  The only scenarios I have found that mention a key or secret is in regards to a Partner Center web app configuration.

Any help would be greatly appreciated!  And let me know if I left anything out that may be useful for debugging.

Thank you!

**Comment by wgbartley** [comment]
After more digging through forums, I figured out the issue.  As of the time of writing (2018-03-12), in the Partner Center user management, the user account needs to have:
 - [Checked] Manages your organization's account as: `Global Admin`
 - [Checked] Business profile admin
 - [Checked] Referrals admin
 - [Checked] Assists your customers as: `Admin agent`

Unfortunately, I couldn't find any official documentation stating these requirements.  I previously only had the "Manages your organization's account as" and "Assists your customers as" checkboxes checked with the corresponding admin values selected.

**Comment by alidhia** [comment]
Hi @wgbartley,

I'm glad you found a solution to your issue. however, you need only the last role you mentioned to see customer profiles which are the "Admin Agent" the global admin, business profile admin or referral admin is not needed for this operation. 

we will try to update the documentation to reflect this.

Thanks,
Ali
