### ISSUE TITLE
The user or administrator has not consented to use the application with ID 'xxx' named 'AppName'. Send an interactive authorization request for this user and resource

### ISSUE THREAD

**Issue by ITCareNV** [PartnerCenterSamples/Partner-Center-SDK-Samples#39]
Dear community

We are trying to have a look at the Partner-Center-SDK-Samples project to see what and how we could implement certain features/functionalities within this sample. We have registered an Native app in the Azure portal, granted ALL permissions available and than clicking on the "grant permission" button in the portal as well as with this url (real values left out) [https://login.microsoftonline.com/TenantNameHere/oauth2/authorize?prompt=admin_consent&client_id=
 ApplicationIdComesHere&response_type=code&redirect_uri= 
 http://localhost&login_hint=AccountLoginHere](url) , we do receive the prompt for all permissions and accept it, how ever (even after + 1 hour waiting) we keep getting this error when authenticating: `**Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException: AADSTS65001: The user or administrator has not consented to use the application with ID 'ApplicationIDHere' named 'PartnerSDKNative'. Send an interactive authorization request for this user and resource.
Trace ID: 877998ed-d3ef-447c-bed7-5ca3996e3100
Correlation ID: 11280449-870a-4364-ba33-cb53772dca8a
Timestamp: 2018-07-03 09:13:00Z ---> System.Net.WebException: The remote server returned an error: (400) Bad Request.**` 

No idea what we are overseeing here ... Account is global admin, rights are granted, ApplicationId is inserted in the app.config along with the rest of values we must provide. I can see in the manifest that   "oauth2Permissions": [], is empty, shouldn't that be filled with the permissions we granted?

We have followed the following steps from these sources but with no success: [https://www.koskila.net/2017/11/20/how-to-fix-admin-consent-issues-aadsts65001/  ](url)

[https://social.msdn.microsoft.com/Forums/sqlserver/en-US/d091b15d-8e5d-467b-9ea4-b947ae78dc81/the-user-or-administrator-has-not-consented-to-use-the-application-with-id-xxxxxx-send-an?forum=partnercenterapi](url)

[https://www.red-gate.com/simple-talk/cloud/security-and-compliance/azure-active-directory-part-3-developing-native-client-applications/](url)

Does anyone have any suggestions?
Thank you in advance!

**Comment by SalmanMukhtar** [comment]
Hi,

Did you also register that app on https://partnercenter.microsoft.com under "App Management"?

Take a look at this https://www.youtube.com/watch?v=8RRssasC2Ys&feature=youtu.be
Might be helpful.

Regards,
Salman

**Comment by ITCareNV** [comment]
Hi Salman

Thank you for your reply, this was actually the only step we couldn't perform because we didn't find this area when logging in with the global admin account. I think the issue here is due to the type of account we tried with, it is a global admin account but not our main partner account i think, i will ask our IT manager when he is back next week to have access to that account so we can configure it properly.

I will get back to you with the results next week in the hope that this will solve our issue.
Kind regards!

**Comment by SalmanMukhtar** [comment]
Hi,

Happy to help and best of luck :-)

Regards,
Salman

**Comment by ITCareNV** [comment]
Hi @SalmanMukhtar 

So we have managed to get it working using a partner account, i was a little confused between the accounts that we had available for us to use hence the issues using the sample. 

Everything works like a charm now, amazing contribution, thank you guys and thank you @SalmanMukhtar  for your help!

Issue can be closed.

Kind regards
