### ISSUE TITLE
Azure usage data timespan

### ISSUE THREAD

**Issue by brooksca** [PartnerCenterSamples/Partner-Center-SDK-Samples#44]
From what period is the data returned from `partnerOperations.Customers.ById(customerId).Subscriptions.ById(subscriptionId).UsageRecords.Resources.Get()`? Is it the current billing period, the last 90 days? 

I can't find any information about this in the docs (https://docs.microsoft.com/en-us/partner-center/develop/get-a-subscriptions-resource-usage-information). Any help would be much appreciated.

**Comment by alidhia** [comment]
Hi @brooksca , the data returned by this API is for the current billing period.

I am going to close this issue but please feel free to re-open it if you have more questions.
