### ISSUE TITLE
CSP program new mandatory security requirements 

### ISSUE THREAD

**Issue by SalmanMukhtar** [PartnerCenterSamples/Partner-Center-SDK-Samples#45]
Hi,

**Does following requirements from Microsoft effects partner center API.
What needs to be done?**

**Impacted Audience**
Partners transacting in the CSP program using CSP capabilities and APIs in the partner center (Indirect providers, direct bill partners and CSP indirect resellers)
Control panel vendors who integrate their solutions with APIs in the partner center 

**Summary**
We have noticed an increasing number of security breaches and fraud incidents in the industry. As our Cloud Solution Provider (CSP) program ecosystem grows, we are extending our secure application model and best practices to our partner ecosystem. We are introducing new mandatory security requirements that help protect our partners in the CSP program ecosystem, as well as customers, from potential security risks caused by unauthorized access to CSP capabilities in the partner center.

**The new security requirements include**:
1. Enabling a new secure application model to integrate with APIs in the partner center
2. Adopting and enabling Multi-Factor Authentication (MFA) to access CSP capabilities and APIs in the partner center 

These requirements will enable all parties, including partners in the CSP program, control panel vendors and customers to better protect their infrastructure as well as customer data from potential security risks such as identify theft or other fraud incidents.

**Partner Action Required**: 
1. Enabling a new secure application model to integrate with APIs in the partner center
•	All control panel vendors and partners in the CSP program who integrate their solutions with Partner Center APIs need to enable the new secure application model 
•	Timeline
•	Implementation due date: **December 11, 2018**
•	Requirement enforcement date begins **February 4, 2019**
•	Starting **February 4, 2019**, partners who don’t meet these security requirements will not be able to transact through APIs in the partner center. 
Partner scenarios/Actions required
1. Partners using APIs directly (Indirect providers, direct bill partners) 
•	Start implementing this requirement immediately. Refer to this document – [Partner center: secure application model guide.](url)

**Comment by alidhia** [comment]
Hi @SalmanMukhtar,

The requirements do apply to Partner Center APIs, what you have posted is for Partner API. please see https://docs.microsoft.com/en-us/partner-center/develop/enable-secure-app-model for more details about what needs to be done.

Thanks,
Ali

**Comment by SalmanMukhtar** [comment]
Hi @alidhia ,

Thanks for the answer. I just wanted to know that are above requirements applied on "Partner-Center-SDK-Samples" too?

Regards,
Salman

**Comment by alidhia** [comment]
Hi @SalmanMukhtar,

Yes, we have work planned to change how we authenticate in the samples soon in the new samples repo which is located at https://github.com/Microsoft/Partner-Center-DotNet-Samples.

Thanks,
Ali
