### ISSUE TITLE
Retrieve Customers more than 500

### ISSUE THREAD

**Issue by kailashnk** [PartnerCenterSamples/Partner-Center-SDK-Samples#5]
Hi,

I am retrieving customers from Partner center using partner center API. This API pulls up to 500 records. How can I retrieve more than 500 customers because I am having more than 500 customers. Please any one  
help to resolve this issue.

Thanks,
Kailash.n6@gmail.com

**Comment by RaedJarrar** [comment]
Check the GetPagedCustomers class. It already does that. Notice the use of enumerator which internally parses the next link which provides the next set of customers.

**Comment by kailashnk** [comment]
Hi
Thanks for your reply. It works great.

Thank you,
Kailasam
