### ISSUE TITLE
Exception: Quantity is not a valid decimal

### ISSUE THREAD

**Issue by SalmanMukhtar** [PartnerCenterSamples/Partner-Center-SDK-Samples#7]
Get an exception when load azure subscription utilization. 
Exception: ""
More information in attached file.

Also it seems it is quite slow to get utilization on 1 subscription for 1 day back? 
Any suggestion?

Regards,
Salman

![capture](https://cloud.githubusercontent.com/assets/24384053/21344377/cf73f036-c69b-11e6-9607-ad2d0ddf3255.JPG)

**Comment by RunOnGitHub** [comment]
+1

**Comment by SalmanMukhtar** [comment]
Hi,

I heard from Microsoft that this has been identified as a bug (already fixed) – release scheduled in Jan.

Regards,
Salman
