### ISSUE TITLE
Azure Utilization Records does not work if the data is in 2 pages.

### ISSUE THREAD

**Issue by laika1234** [PartnerCenterSamples/Partner-Center-SDK-Samples#8]
I'm following https://msdn.microsoft.com/en-us/library/partnercenter/mt791774.aspx to get Utilization Record. But only 1st page is ok. 500 error will be thrown when receiving data in 2nd page. 
It occurs on both REST API and SDK. 

More detail is described in [here](https://social.msdn.microsoft.com/Forums/en-US/c739a55f-e8d9-4cb8-874a-c07dbdb00fc1/error-retrieving-paged-utilization-records-for-azure-in-csp?forum=partnercenterapi).

**Comment by isaiahwilliams** [comment]
Hi @laika1234, this issue should be resolved now. Can you confirm that you are still encountering this issue?
