### ISSUE TITLE
 I can not log in the system through the code, why???

### ISSUE THREAD

**Issue by tsyj211** [PartnerCenterSamples/Partner-Center-SDK-Samples#9]
I can not log in the system through the code, why???

The error is as follows：

“Microsoft.IdentityModel.Clients.ActiveDirectory.AdalServiceException”类型的未经处理的异常在 Microsoft.IdentityModel.Clients.ActiveDirectory.dll 中发生 
其他信息: user_realm_discovery_failed: User realm discovery failed

My app.config :
 `<appSettings>
    <add key="AuthenticationAuthorityEndpoint" value="https://login.chinacloudapi.cn"/>
    <add key="GraphEndpoint" value="https://graph.chinacloudapi.cn"/>
    <add key="CommonDomain" value="common"/>
    <add key="ResourceUrl" value="https://partner.partnercenterapi.microsoftonline.cn"/>
    <add key="RedirectUrl" value="http://localhost"/>    
   <add key="ApplicationId" value="1625564a-b7f3-4b54-a49c-3f4c5f75b5fd"/>
  <add key="UserName" value="admin@cnbmdev.partner.onmschina.cn"/>
    <add key="Password" value="xxxx"/>`

**error picture:**

https://social.msdn.microsoft.com/Forums/getfile/1001051

**Comment by tameemansari** [comment]
I tried this and I wasn't able to repro the issue. Can you please verify your proxy settings? If possible please share a fiddler trace.

**Comment by tsyj211** [comment]
The problem has been solved because of my network problem
Thank you


------------------原始邮件------------------
发件人：  “Tameem Ansari”; <notifications@github.com>;
发送时间：  2017年2月14日（星期二）中午1:26
收件人：  “PartnerCenterSamples / Partner-Center-SDK-Samples”<Partner-Center-SDK-Samples@noreply.github.com>;
抄送：  “wft”<41878925@qq.com>; “作者”<author@noreply.github.com>;
主题：  Re：[PartnerCenterSamples / Partner-Center-SDK-Samples]我无法通过代码登录系统，为什么？（＃9）




我试过这个，我不能重现的问题。您能否验证您的代理设置？如果可能，请分享一个提琴手的痕迹。
 
- 
你收到这个，因为你创作了线程。
直接回复此电子邮件，在GitHub上查看此电子邮件，或将该主题设为静音。
